### ISSUE TITLE
Pequena dúvida sobre intervalos de etiquetas

### ISSUE THREAD

**Issue by phdiegues** [gamuzabrasil/gamuza_labels-magento#1]
Boa tarde.
Antes de mais nada gostaria de parabeniza-lo pelo belo modulo disponibilizado.

Estou com uma pequena dúvida sobra a configuração dos intervalos das etiquetas. Onde consigo estas sequencias dos intervalos?

Muito obrigado.

**Comment by eneiasramos** [comment]
Olá @phdiegues ! Tudo bem?

Os ranges são obtidos através dos Correios.

Att,

**Comment by phdiegues** [comment]
Muito obrigado Eneias!
