### ISSUE TITLE
Erro ao postar objetos nos Correios

### ISSUE THREAD

**Issue by brunohrp** [gamuzabrasil/gamuza_labels-magento#2]
Gerei os objetos pelo módulo e as etiquetas, porém os Correios verificaram erro,
tanto no código de barras quanto nos objetos que não estão cadastrados no SIGEP WEB.

**Comment by eneiasramos** [comment]
Olá @brunohrp ! Tudo bem?

Esse módulo não tem integração com o sigepweb.

Att,
